Initial Dependency Injection implementation
aminecmi/ReaderForSelfoss-multiplatform pull request #32
Opened 2022-07-18 07:57 UTC by davidoskky

## Types of changes

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] This is **NOT** translation related. (See [here](https://github.com/aminecmi/ReaderforSelfoss/pull/170#issuecomment-355715654))

This finishes chore #28 

Hi, I'm starting to work on the Dependency Injection using the Kodein framework and an MVVM architecture.
Since the database is not yet implemented, the scope of this PR is including all the networking code in injected classes; hopefully all of that can be in commonMain.
This first commit just implements the login through dependency injection to test that it works.

(Since I was at it, I also fixed a bug in the login logic which would create problems if you inserted incorrect login information)

2022-07-18 18:26 UTC, aminecmi requested changes

2022-07-18 19:17 UTC, davidoskky commented on shared/build.gradle.kts
> +                implementation("org.kodein.di:kodein-di:7.12.0")
No, in fact I don't need it.
I will remove it

2022-07-18 19:18 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/rest/SelfossApiImpl.kt
> +interface SelfossApi {
For testing, it will allow creating a test implementation which won't need to connect to the real server in order to test the repository which will depend on it.
I forgot to move the interface to a separate file however...

2022-07-18 21:29 UTC, davidoskky commented
I used the library [multiplatform-settings](https://github.com/russhwolf/multiplatform-settings) to have a settings class that is not platform specific.
This is useful for DI because in this way the API Details Service can be implemented in the common source set and makes everything easier to implement since all the networking depends on it and it can now be implemented without worrying about the platform.
Moreover, I feel that the code is a little cleaner and easier to understand.

2022-07-23 08:51 UTC, aminecmi requested changes

2022-07-23 08:51 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/Repository.kt
> +interface Repository {
If this is like the other interface, for testing, then, it's not needed if the testing implementation is not created.

2022-07-23 08:51 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/rest/SelfossApiImpl.kt
> +interface SelfossApi {
If you won't create the testing implementation, there is no need to add the interface.

2022-07-23 08:51 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/Repository.kt
> +    // TODO: remove the items variables in favor of storing everything in the database
As a heads-up, DB storing is an optional setting. It should not be done by default.

2022-07-23 08:51 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        // TODO: Check success, store in DB
You should store in DB only if the setting is true.

2022-07-23 08:51 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        // TODO: Check success, store in DB
This is true for every comment like this.

2022-07-23 08:51 UTC, aminecmi commented on androidApp/src/main/java/bou/amine/apps/readerforselfossv2/android/HomeActivity.kt
> +        api = SelfossApiImpl(
Is this still needed, or is the repository enough ?

2022-07-23 08:51 UTC, aminecmi commented on androidApp/src/main/java/bou/amine/apps/readerforselfossv2/android/ReaderActivity.kt
> +        api = SelfossApiImpl(
Is this still needed, or is the repository enough ?

2022-07-23 08:51 UTC, aminecmi commented on androidApp/src/main/java/bou/amine/apps/readerforselfossv2/android/background/background.kt
> +        val api = SelfossApiImpl(
Is this still needed, or is the repository enough ?

2022-07-23 10:47 UTC, davidoskky commented on androidApp/src/main/java/bou/amine/apps/readerforselfossv2/android/HomeActivity.kt
> +        api = SelfossApiImpl(
I'm still working on this, eventually I will remove SelfossApi and ApiDetailsService from every activity and substitute it with the repository
It is currently needed, but I will remove it in the next commits.

2022-07-23 10:48 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/Repository.kt
> +    // TODO: remove the items variables in favor of storing everything in the database
Sure

2022-07-24 18:45 UTC, aminecmi requested changes

2022-07-24 18:45 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +    get() { return ArrayList(field) }
`items` is already an `ArrayList`. Is there any reason to create a new `ArrayList` each time the getter is called ?

Same for the setter.

2022-07-24 18:45 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        tmpItems.addAll(fetchedItems)
I don't understand why you remove items then add them back. Is it to update the existing ones ?
```

2022-07-24 18:45 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        val dateUtils = DateUtils(apiMajorVersion)
This should be a field so it's not instantiated every time.

2022-07-24 18:45 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        if (selectedType == "unread") {
This appears to be called before and after an api call.

As the api call takes the type of item we want, this will have no effect, still it will instantiate an array list, and will try to do multiple filters on the list.

2022-07-24 18:45 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +            markAsReadLocally(id)
This will do nothing, because the item is `ureand == false`

2022-07-24 18:45 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        if (response != null) {
This can be `return response != null`

2022-07-24 18:45 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +            Napier.e(cause.message!!, tag = "1")
The tag should be something explicit, other than "1"

2022-07-24 18:45 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        baseUrl = apiDetails.getBaseUrl()
If you make an api call with a specific baseUrl, I don't think it'll change.

2022-07-25 11:48 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        tmpItems.addAll(fetchedItems)
Yes, otherwise edits done through the web interface would never be registered by the application.

2022-07-25 11:49 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        val dateUtils = DateUtils(apiMajorVersion)
Yes, I'm still thinking about this as I have to analyze where it's used, it could probably be injected too.

2022-07-25 11:52 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        if (selectedType == "unread") {
I am storing all the articles in the items variable.
The repository does not return the results of the api call, but the contents of the items variable.

After I finished stripping the other classes from the Home activity, I will change the logic, so that no redundant api call is done.

2022-07-25 11:54 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +            markAsReadLocally(id)
Ooops, wrong function...

2022-07-25 11:57 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +            Napier.e(cause.message!!, tag = "1")
Right, I just copied this from the original function

2022-07-25 11:58 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        baseUrl = apiDetails.getBaseUrl()
This is needed before the login is done.
The repository is used to do the login; if you insert the wrong url and do the login again, this function will be called to correct the url.

2022-07-25 12:01 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        tmpItems.addAll(fetchedItems)
This code seems a little complicated. Could this be simplified ?

2022-07-25 12:01 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +    get() { return ArrayList(field) }
I wish to make a copy of the object, so that other classes cannot directly modify the content of the repository.

2022-07-25 12:02 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        if (selectedType == "unread") {
> I am storing all the articles in the items variable.

I don't think this is a good idea. You may want to store each item type in a different variable, so you don't have to filter.

2022-07-25 12:04 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        baseUrl = apiDetails.getBaseUrl()
If the url is wrong, then the variable should be changed with the user input, not the api result.

2022-07-25 13:24 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        if (selectedType == "unread") {
I think this is a better option; the variable containing all articles would duplicate data about unread articles and favorites.
Moreover, this way we don't need a different behavior for handling the database: in the database all articles will be stored in the same table and thus filtering will be required.

Also, this allows minimizing the amount of api calls, making the application faster.
Let's say I go in the tab with all articles and download a bunch of articles there, once I go back to the unread tab all the articles are already downloaded and you don't need to wait for them to download again.

2022-07-25 13:25 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +            Napier.e(cause.message!!, tag = "1")
Do you have advices about how I should tag logs?
Something like reader for selfoss or maybe something class related, like SelfossRepository?

2022-07-25 13:27 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        tmpItems.addAll(fetchedItems)
As far as I understand it, removing items and then adding them back again is the only way to update items in an ArrayList.
I could create a dedicated function to perform the update, so that you don't need to see all this operations being done.

2022-07-25 15:09 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        tmpItems.addAll(fetchedItems)
I was thinking about something like this
```
        val fetchedIDS = fetchedItems.map { it.id }
        val tmpItems = ArrayList(items).map( item -> {
           return fetchedItems.first {it.id == item.id}.orElse(item)
        })
```

2022-07-25 15:22 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        if (selectedType == "unread") {
This will cause inconsistencies, and you'll need to make 3 api calls for items if you store everything in a variable.

Say you only read new items, if you do an api call with no `type` set.
This will result in fetching X unread + Y read + Z starred items. Yet, in the settings, you set that you want to fetch X+Y+Z articles
So you'll need to make each api call with the same number of items, but you don't need to, as the user do only read new items.

> the variable containing all articles would duplicate data about unread articles and favorites.

So, the items variable should only contain the items of the currently selected type.

> Moreover, this way we don't need a different behavior for handling the database: in the database all articles will be stored in the same table and thus filtering will be required.

The DB will be containing all items, but the DB usage is optional, and should only be used as a fallback.
It should be used to display items before the first api call is finished, and to store the api "actions" until the next time the network is available.

> Also, this allows minimizing the amount of api calls, making the application faster.

The app will not be slower, because the api calls are non-blocking

2022-07-25 15:24 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +            Napier.e(cause.message!!, tag = "1")
Something like `FileName.FunctionName` would be the best.

2022-07-25 16:07 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        if (selectedType == "unread") {
> you'll need to make 3 api calls for items if you store everything in a variable

Not necessarily, I'll just make the call to fetch unread articles if the user stays in the unread tab and only fetch read items when he switches tab.

> The app will not be slower, because the api calls are non-blocking

While api calls are non-blocking, you still have to wait for the result of the call each time you switch tab as it is implemented now. You won't see the articles you require until the api call is complete: thus if you switch from unread to favorites, you will keep seeing the unread articles until the api call is complete.

> You may want to store each item type in a different variable

Even doing this wouldn't eliminate the filtering step, since you would have to filter according to selected tag, source and search.
If we don't store the articles, an api call will have to be done each time you switch to another tag or source.

2022-07-25 16:42 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        if (selectedType == "unread") {
> > you'll need to make 3 api calls for items if you store everything in a variable
> 
> Not necessarily, I'll just make the call to fetch unread articles if the user stays in the unread tab and only fetch read items when he switches tab.

So you will iterate over every single item of the list even if you don’t need to. I really don’t think this is great.

> 
> > The app will not be slower, because the api calls are non-blocking
> 
> While api calls are non-blocking, you still have to wait for the result of the call each time you switch tab as it is implemented now. You won't see the articles you require until the api call is complete: thus if you switch from unread to favorites, you will keep seeing the unread articles until the api call is complete.

I don’t see any issue with this. The app is a reader that uses a selfoss instance that is the source of truth. The local database could be used *if enabled*, je not, a call is made.

> 
> > You may want to store each item type in a different variable
> 
> Even doing this wouldn't eliminate the filtering step, since you would have to filter according to selected tag, source and search. If we don't store the articles, an api call will have to be done each time you switch to another tag or source.

Searching must not be done locally. Searching locally will not return any result of there is no match in the local data, but there is on the selfoss instance.

2022-07-25 18:26 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        if (selectedType == "unread") {
Just to clarify how I see things :

- Every navigation/search/action should lead to an api call
- If the user **did not** enable data caching
  - In case of connectivity issues, we don't do any api call until the network is available. Filtering/searching should not work either.
- If the user **did** enable data caching
  - On normal network availability, the data is loaded with data from the api, and kept up to date after each action. Still, every navigation/search/filtering should lead to an api call.
  - In case of connectivity issues, the DB is a temporary mean of reading articles. Every action is stored in the DB, and will be replayed when the network is available. Filtering/searching will use the local data.

2022-08-01 11:31 UTC, davidoskky commented
I'm sorry I disappeared for a while; I'll be back in a week or two.

2022-08-13 19:07 UTC, aminecmi requested changes
This PR is getting bigger and bigger, and it seems to be outside the issue scope.

Maybe try to fix the remaining comments, add the remaining dependency injections everywhere, and I'll merge this.

2022-08-13 19:07 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        if (items.first {it.id == id}.unread) {
This doesn't seem efficient. 

First, this is called inside a for loop
```
            for (id in ids) {
                markAsReadLocally(id)
            }
```

and then, you search for the item inside `items` (another loop)

You should do this differently so `markAsReadLocally` takes an item and the caller handle the item fetching.


The following functions should be handled like this too.

2022-08-13 20:56 UTC, davidoskky commented
Yes, I was also thinking this is a good point to merge.
In a next PR I will include the network checks directly inside the repository so that all that logic can be removed from the activities.
I'll fix these issues in the next days.

2022-08-14 10:43 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +    private fun filterSelectedItems(items: ArrayList<SelfossModel.Item>): ArrayList<SelfossModel.Item> {
No, but I'll keep it for now; it might be useful to execute filtering while offline.

2022-08-14 11:04 UTC, davidoskky commented on androidApp/src/main/java/bou/amine/apps/readerforselfossv2/android/adapters/ItemListAdapter.kt
> +            if (itm.getThumbnail(repository.baseUrl).isEmpty()) {
I believe this might be possible, but I don't think it's a good way to go about it.
Having the parameter is better than having the repository injected everywhere, injecting is time consuming and items get created and destroyed all the time.

2022-08-14 11:05 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +    get() { return ArrayList(field) }
Do you have advice on how to handle this?

2022-08-14 11:50 UTC, aminecmi commented on androidApp/src/main/java/bou/amine/apps/readerforselfossv2/android/adapters/ItemListAdapter.kt
> +            if (itm.getThumbnail(repository.baseUrl).isEmpty()) {
Ok, let's keep it this way.

2022-08-14 12:04 UTC, aminecmi requested changes

2022-08-14 12:04 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +    get() { return ArrayList(field) }
I see two solutions:

1. Don't update items outside the repository. (This is pretty simple)
2. Use some library like [this](https://github.com/Kotlin/kotlinx.collections.immutable) and use an `ImmutableList`

2022-08-14 15:36 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +    get() { return ArrayList(field) }
If it's just about not updating it outside the repository, then we can do that and avoid introducing more libraries.
I'm moderately sure nothing is currently updating items outside the repository, and even if it is it should be corrected in the next refactoring of the activities since all direct access will have to be removed anyways.

2022-08-14 18:22 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +    get() { return ArrayList(field) }
Ok for me.

2022-08-15 13:28 UTC, davidoskky commented
What is the purpose of obtaining the initial tab from the intent?
It is not a setting that can be changed; can I remove this and make elementsShown an ItemType?

HomeActivity.OnCreate
```
        if (fromTabShortcut) {
            elementsShown = intent.getIntExtra("shortcutTab", UNREAD_SHOWN)
        }
```

2022-08-15 18:11 UTC, aminecmi commented
> What is the purpose of obtaining the initial tab from the intent? It is not a setting that can be changed; can I remove this and make elementsShown an ItemType?
> 
> HomeActivity.OnCreate
> 
> ```
>         if (fromTabShortcut) {
>             elementsShown = intent.getIntExtra("shortcutTab", UNREAD_SHOWN)
>         }
> ```

These are located in the `shortcuts.xml`

```
    <shortcut
        android:shortcutId="favs"
        android:enabled="true"
        android:icon="@drawable/ic_tab_favorite_black_24dp"
        android:shortcutShortLabel="@string/tab_favs">
        <intent
            android:action="android.intent.action.VIEW"
            android:targetPackage="apps.amine.bou.readerforselfoss"
            android:targetClass="apps.amine.bou.readerforselfoss.HomeActivity">
            <extra
                android:name="shortcutTab"
                **android:value="3" />**
        </intent>
    </shortcut>
```

You should change the `android:value` value to the enum value.

2022-08-15 18:15 UTC, aminecmi requested changes

2022-08-15 18:15 UTC, aminecmi commented on androidApp/src/main/java/bou/amine/apps/readerforselfossv2/android/HomeActivity.kt
> +                UNREAD_SHOWN -> getItems(appendResults, ItemType.UNREAD)
`elementsShown` should be the enum. You'll just have `getItems(appendResults, elementsShown)`

2022-08-15 18:45 UTC, davidoskky commented
Alright, the application appears to work correctly.
I believe we can merge this and I'll keep working on the repository in another PR.

2022-08-16 07:39 UTC, aminecmi requested changes

2022-08-16 07:39 UTC, aminecmi commented on androidApp/src/main/java/bou/amine/apps/readerforselfossv2/android/MyApp.kt
> +        if (settings.getString("unique_id", "").isEmpty()) {
This should be removed. It is not used anymore.

2022-08-16 07:39 UTC, aminecmi commented on androidApp/src/main/java/bou/amine/apps/readerforselfossv2/android/ReaderActivity.kt
> -                editor.putInt("text_align", ALIGN_LEFT)
The two `text_align` changes are the same (except the value change) and could be refactored.

2022-08-16 07:39 UTC, aminecmi commented on androidApp/src/main/java/bou/amine/apps/readerforselfossv2/android/background/background.kt
> +        val api = SelfossApiImpl(
This is still relevant. Please don't resolve the issues yourself.

2022-08-16 07:39 UTC, aminecmi commented on androidApp/src/main/java/bou/amine/apps/readerforselfossv2/android/background/background.kt
> +    private val apiDetailsService : ApiDetailsService by instance()
This shouldn't be needed anymore.

2022-08-16 07:39 UTC, aminecmi commented on androidApp/build.gradle.kts
> +    implementation("org.kodein.di:kodein-di:7.12.0")
This is imported in the shared gradle file. Is it still needed here ?

2022-08-16 07:39 UTC, aminecmi commented on androidApp/build.gradle.kts
> +    implementation("com.russhwolf:multiplatform-settings-no-arg:0.9")
This is imported in the shared gradle file. Is it still needed here ?

2022-08-16 07:39 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/Repository.kt
> +interface Repository {
Please remove this until the tests are implemented.

2022-08-16 07:39 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +            items = ArrayList(fetchedItems)
This is still relevant. Please don't resolve the issues yourself.

2022-08-16 07:39 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        tmpItems.addAll(fetchedItems)
Did you look into simplifying this ?

2022-08-16 07:39 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +    private fun filterSelectedItems(items: ArrayList<SelfossModel.Item>): ArrayList<SelfossModel.Item> {
If it's not used, please remove it.

2022-08-16 07:39 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +    override suspend fun markAsRead(id: Int): Boolean {
You can pass the item instead of the id, so you won't have to do `items.first {it.id == id}` later.

2022-08-16 07:39 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +    override suspend fun unmarkAsRead(id: Int): Boolean {
You can pass the item instead of the id, so you won't have to do `items.first {it.id == id}` later.

2022-08-16 07:39 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +    override suspend fun starr(id: Int): Boolean {
You can pass the item instead of the id, so you won't have to do `items.first {it.id == id}` later.

2022-08-16 07:39 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +    override suspend fun unstarr(id: Int): Boolean {
You can pass the item instead of the id, so you won't have to do `items.first {it.id == id}` later.

2022-08-16 07:39 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +    override suspend fun markAllAsRead(ids: List<Int>): Boolean {
Can you pass the items instead of the ids ?

2022-08-16 07:39 UTC, aminecmi commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/rest/SelfossApiImpl.kt
> +interface SelfossApi {
If there are no tests implemented, please remove this.

2022-08-16 07:42 UTC, aminecmi commented
> Alright, the application appears to work correctly. I believe we can merge this and I'll keep working on the repository in another PR.

There are still unresolved comments. Once they are all resolved, I'll test the app one last time and merge everything.

2022-08-16 08:51 UTC, davidoskky commented on androidApp/src/main/java/bou/amine/apps/readerforselfossv2/android/LoginActivity.kt
> +                        CoroutineScope(Dispatchers.Main).launch {
Yes, this is needed because the UI cannot be updated from the IO Dispatcher.

2022-08-16 08:58 UTC, davidoskky commented on androidApp/src/main/java/bou/amine/apps/readerforselfossv2/android/ReaderActivity.kt
> -                editor.putInt("text_align", ALIGN_LEFT)
Should I refactor this in this PR? This is not related to the DI

2022-08-16 09:15 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +    override suspend fun unmarkAsRead(id: Int): Boolean {
This currently cannot be done, because actions need to mark articles but only store the id.

2022-08-16 09:16 UTC, aminecmi commented on androidApp/src/main/java/bou/amine/apps/readerforselfossv2/android/ReaderActivity.kt
> -                editor.putInt("text_align", ALIGN_LEFT)
Yes please, since it is updated here.

2022-08-16 09:24 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +            items = ArrayList(fetchedItems)
fetchedItems is not an ArrayList, it has to be cast to one.

2022-08-16 09:42 UTC, davidoskky commented on shared/src/commonMain/kotlin/bou/amine/apps/readerforselfossv2/repository/RepositoryImpl.kt
> +        tmpItems.addAll(fetchedItems)
I wasn't able to simplify it more than this.
The way you advised does not work and I did not find a way to make it work.

2022-08-16 10:03 UTC, davidoskky commented
This should be everything

2022-08-16 11:46 UTC, aminecmi commented
> This should be everything

There are still some unresolved issues.

2022-08-16 12:02 UTC, davidoskky commented on androidApp/build.gradle.kts
> +    implementation("org.kodein.di:kodein-di:7.12.0")
Yes, it is needed here.
It is used in the android specific files as well

2022-08-16 12:03 UTC, davidoskky commented on androidApp/build.gradle.kts
> +    implementation("com.russhwolf:multiplatform-settings-no-arg:0.9")
Yes

2022-08-16 18:42 UTC, merged

2022-08-16 18:44 UTC, aminecmi commented
There are two bugs that I found while testing, but are unrelated to the PR, so I merged it.

I'll fix the last comment, now.

2022-08-16 19:14 UTC, aminecmi commented
@davidoskky the project will be moved to https://gitea.amine-louveau.fr/Louvorg/ReaderForSelfoss-multiplatform

You'll be able to create an account, fork the project and just change the remote url from the project.